ci:
  skip:
    - poetry-lock  # no network

minimum_pre_commit_version: 2.17.0
repos:
  - repo: https://github.com/cielquan/mirrors-poetry
    rev: 1.1.13
    hooks:
      - id: poetry-check
      - id: poetry-lock
        args: ["--no-update"]
      - id: poetry-export
